spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_playground
    username: hannie
    password: asdf

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  batch:
    job:
      enabled: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
